#pragma once

#include QMK_KEYBOARD_H

#define DF_BASE DF(LY_BASE)
#define DF_GAME DF(LY_GAME)
// MOD_MEH = MOD_LCTL | MOD_LALT | MOD_LSFT
// MOD_HYPR = MOD_LCTL | MOD_LALT | MOD_LGUI | MOD_LSFT
#define MOD_ASTRAL  MOD_LGUI | MOD_LALT | MOD_LSFT
#define MOD_NEXUS   MOD_LCTL | MOD_LGUI | MOD_LSFT
#define MOD_TRINITY MOD_LCTL | MOD_LGUI | MOD_LALT
#define OS_CMD OSM(MOD_LGUI)
#define OS_CTL OSM(MOD_LCTL)
#define OS_OPT OSM(MOD_LALT)
#define OS_SFT OSM(MOD_LSFT)
#define OS_MEH OSM(MOD_MEH)
#define OS_HYP OSM(MOD_HYPR)
#define OS_ASTRAL  OSM(MOD_ASTRAL)
#define OS_NEXUS   OSM(MOD_NEXUS)
#define OS_TRINITY OSM(MOD_TRINITY)
